# Workflow = Pipeline
name: Demo on triggers
#What makes this pipeline trigger
on: 
    workflow_dispatch:
  # 1. Manual trigger with inputs
      inputs:
        build_id:
          required: true
          type: number
        deploy_target:
          required: true
          type: string
        perform_deploy:
          required: true
          type: boolean
  # pull_request:
  #   branches:
  #     - main
  #   types:                    # default types: opened, synchronize, reopened
  #     - opened
  # push:
  #   branches:
  #     - 'main'
env:
  APP_NAME: "devsecops-app"
  APP_VERSION: "1.0.0"
  DOCKER_REGISTRY: "ghcr.io"
  NODE_VERSION: "20"

# stages
jobs:
  # stage
  say-hello:
    runs-on: ubuntu-latest # The virtual machine environment
    steps:
      # - name: Greet the world
      #   run: echo "Hello from main branch!"
      - name: Greet the world
        run: echo "Hello from main branch pull request!"

  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build ID: ${{ inputs.build_id }}"
          echo "to target:${{ inputs.deploy_target }}"

  access-env:
    steps:
      - run: |
          echo "App Name: $APP_NAME"
          echo "App Version: $APP_VERSION"
          echo "Docker Registry: $DOCKER_REGISTRY"
          echo "Node Version: $NODE_VERSION"
      
