# Workflow = Pipeline
name: context
#What makes this pipeline trigger
on: [push] # Triggers the workflow on every push to the repository

# stages
jobs:
  # stage
  say-hello:
    runs-on: ubuntu-latest # The virtual machine environment
    steps:
      - name: print github context
        run: echo '${{ toJSON(github) }}'

      - name: access secrets and variables
        run: |
          echo "DB User is: ${{ secrets.DB_USER }}"
          echo "DB Password is: ${{ secrets.DB_PASSWORD }}"
          echo "DB URL is: ${{ vars.DB_URL }}"

      - name: Compute tag
        id: tag                                    # step MUST have an id
        run: echo "value=myapp:abc123" >> $GITHUB_OUTPUT

      - name: Use that output
        run: echo "Image is ${{ steps.tag.outputs.value }}"